### PR TITLE
Fix permissions

### PR DESCRIPTION
**Pull request by 42wim**
Make it work for non-root users

### CODE REVIEW

**Review by dmitshur — APPROVED** [review]

**Comment by campoy** [comment]
dear CLA bot, could you check?

**Comment by campoy** [comment]
It seems the bot is sleepy today, but I checked manually and I'll need you to sign this CLA to merge your changes @42wim 

https://cla.developers.google.com/

Thanks so much for your contribution, and thanks @shurcooL for reviewing!

**Comment by 42wim** [comment]
Hi, sorry I don't feel comfortable signing that CLA.

**Comment by campoy** [comment]
Ok, then I'll close this PR. Thanks

**Pull request closed without merging**
